server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: stripe-mock

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,traces
  endpoint:
    prometheus:
      enabled: true

logging:
  include-details: true