name: Deploy Applications
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Select the target environment'
        options:
          - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: hello_world
            language: python
            context-path: services/hello_world
    name: Test ${{ matrix.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python tests
        if: matrix.language == 'python'
        uses: ./.github/actions/test-python
        with:
          context-path: ${{ matrix.context-path }}

  deploy_ecs_cluster_stack:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy ecs_cluster stack
        uses: ./.github/actions/terraform_apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: ecs_cluster

  deploy_container_registry_stack:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy container_registry stack
        uses: ./.github/actions/terraform_apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: container_registry

  build_and_push:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: [test, deploy_container_registry_stack]
    strategy:
      matrix:
        include:
          - name: hello_world
            ecr-repo: api_hello_world
            context-path: services/hello_world
    name: Build and Push ${{ matrix.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Docker Image to ECR
        uses: ./.github/actions/build_image
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecr-repo: ${{ matrix.ecr-repo }}
          image-tag: latest
          context-path: ${{ matrix.context-path }}

  deploy_monitoring_stack:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: [deploy_ecs_cluster_stack]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy monitoring stack
        uses: ./.github/actions/terraform_apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: monitoring

  deploy_database_stack:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: [deploy_ecs_cluster_stack]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy database stack
        uses: ./.github/actions/terraform_apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: database

  deploy_ecs_api_stack:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: [build_and_push, deploy_database_stack, deploy_ecs_cluster_stack]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy ecs_api stack
        uses: ./.github/actions/terraform_apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: ecs_api

  deploy_api_gateway_stack:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: [deploy_ecs_api_stack]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy api_gateway stack
        uses: ./.github/actions/terraform_apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: api_gateway
