name: Destroy Infrastructure
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Select the target environment'
        options:
          - develop

jobs:
  destroy_web_app_stack:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Destroy web_app
        uses: ./.github/actions/terraform_destroy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: web_app

  destroy_api_gateway_stack:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ destroy_web_app_stack ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Destroy api_gateway
        uses: ./.github/actions/terraform_destroy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: api_gateway

  destroy_ecs_api_stack:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ destroy_api_gateway_stack ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Destroy ecs_api
        uses: ./.github/actions/terraform_destroy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: ecs_api

  destroy_database_stack:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ destroy_ecs_api_stack ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Destroy database
        uses: ./.github/actions/terraform_destroy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: database

  destroy_monitoring_stack:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ destroy_ecs_api_stack ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Destroy monitoring
        uses: ./.github/actions/terraform_destroy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: monitoring

  destroy_ecs_cluster_stack:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ destroy_ecs_api_stack, destroy_monitoring_stack ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Destroy ecs_cluster
        uses: ./.github/actions/terraform_destroy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: ecs_cluster

  destroy_cognito_stack:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ destroy_ecs_api_stack, destroy_api_gateway_stack ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Destroy cognito
        uses: ./.github/actions/terraform_destroy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          terraform_environment: ${{ inputs.environment }}
          terraform_stack: cognito

#  destroy_container_registry_stack:
#    runs-on: ubuntu-latest
#    environment: ${{ inputs.environment }}
#    needs: [destroy_ecs_api_stack]
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Terraform Destroy container_registry
#        uses: ./.github/actions/terraform_destroy
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#          terraform_environment: ${{ inputs.environment }}
#          terraform_stack: container_registry
